/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define TESTS_LEN 5
#define OUTPUT_LEN 10
#define STR_LEN 256

struct Input {
	char *strType;
	int intType;
};
typedef struct Input Input;

struct TestStruct {
	char *id;
	char *bookerId;
	char *brand;
	char *imagesFolder;
};
typedef struct TestStruct TestStruct;

struct Output {
	TestStruct tests[OUTPUT_LEN];
};
typedef struct Output Output;

#define SERVPROG 0x20000020
#define SERVVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define with_input_struct 1
extern  int * with_input_struct_1(Input *, CLIENT *);
extern  int * with_input_struct_1_svc(Input *, struct svc_req *);
#define with_output_struct 2
extern  Output * with_output_struct_1(char *, CLIENT *);
extern  Output * with_output_struct_1_svc(char *, struct svc_req *);
extern int servprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define with_input_struct 1
extern  int * with_input_struct_1();
extern  int * with_input_struct_1_svc();
#define with_output_struct 2
extern  Output * with_output_struct_1();
extern  Output * with_output_struct_1_svc();
extern int servprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_TestStruct (XDR *, TestStruct*);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_Input ();
extern bool_t xdr_TestStruct ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
